version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend

  app:
    container_name: app
    restart: always
    build: .
    image: project_app
    environment:
      - VIRTUAL_HOST=chat.local
      - VIRTUAL_PORT=3000
    expose:    # strictly informational
      - "3000"
    depends_on:
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - chat-volume:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  chat-volume:
